services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: voltstream-broker
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15
    container_name: voltstream-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voltstream_pricing
    ports:
      - "5432:5432"