spring.application.name=pricing-service

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/voltstream_pricing
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

