spring.application.name=billing-service
server.port=8081

# -------------------------
# RABBITMQ CONNECTION
# -------------------------
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# -------------------------
# DATABASE CONNECTION
# -------------------------
# We are connecting to the exact same Postgres container/database here for simplicity. 
# Hibernate will just create the 'invoice_record' table right next to the 'pricing_record' table.
spring.datasource.url=jdbc:postgresql://postgres-billing:5432/billing_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

